name: bitsgap_test
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  mobx: ^2.4.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^2.6.2
  json_serializable: ^6.8.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/


